### PR TITLE
[MSHARED-887] set Maven 3.1.0 as minimum and cleanup dependencies

### PR DESCRIPTION
**Pull request by elharo**

### CODE REVIEW

**Comment by slachiewicz** [comment]
https://github.com/apache/maven-shared-jar/commit/580f53c1b63a7630cb3a70822035f4531bfadf2b

**Comment by elharo** [comment]
That code doesn't seem to be in HEAD?

**Comment by elharo** [comment]
@slachiewicz After looking at that commit, the difference seems to be that this PR imports plexus-containers-default and that one imports org.eclipse.sisu.plexus. 

I'm not sure why one should be chosen over the other or why two different artifacts provide the same classes.

**Comment by slachiewicz** [comment]
I use the plexus version that was imported by the Maven 3.1 dependencies (3.1.1 already has a different version). It seems to me that if we use a newer version of Plexus and someone uses the classes/methods that were available before then this plugin may not work properly. I think Maven 3.1 will use artifacts that are provided by Core (https://github.com/apache/maven/blob/master/maven-core/src/main/resources/META-INF/maven/extension.xml)

**Comment by jira-importer** [comment]
Resolve #82

**Pull request closed without merging**
