### PR TITLE
[MSHARED-1411] - Allow to access the root content entries...

### PR DESCRIPTION
**Pull request by belingueres**
...if it is a multi-release JAR file

### CODE REVIEW

**Comment by michael-o** [comment]
We need to bush back because of https://issues.apache.org/jira/browse/MSHARED-1413.

**Comment by michael-o** [comment]
I have a general question to you and would like to know your opinion: After giving it more thought, what makes more sense to you: Name it "Root" or rather "Unversioned" which makes it consitent with "Versioned". Let me know what you think.

**Comment by belingueres** [comment]
Between Root and Unversioned, I prefer Root.
The [JAR file spec](https://docs.oracle.com/en/java/javase/22/docs/specs/jar/jar.html)  references it as "root" or "top-level":

> Classes and resource files dependent on a major version, 9 or greater, of a Java platform release may be located under a versioned directory instead of under the top-level (or root) directory.

**Comment by michael-o** [comment]
> Between Root and Unversioned, I prefer Root. The [JAR file spec](https://docs.oracle.com/en/java/javase/22/docs/specs/jar/jar.html) references it as "root" or "top-level":
> 
> > Classes and resource files dependent on a major version, 9 or greater, of a Java platform release may be located under a versioned directory instead of under the top-level (or root) directory.

You convined me. Thanks!

**Review by michael-o — APPROVED** [review]

**Pull request closed without merging**
